apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Grype
  description: 
    A vulnerability scanner for container images and filesystems
  links:
    - title: Website
      url: https://github.com/PhoenixRedflash/grype
    - title: Documentation
      url: https://github.com/anchore/grype/blob/main/README.md
    - title: Security scan
      url: https://eteamspace.internal.ericsson.com/display/EWS/Security+Scan+for+Grype
  annotations:
    github.com/project-slug:  "PhoenixRedflash/Grype" 
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: "Group:sre"
  lifecycle: experimental
